name: note
description: Note application

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # sqf lite for store data in our phone database
  sqflite: ^2.0.3
  sqflite_common_ffi: ^2.0.0

  # display datetime format
  intl: ^0.17.0

  # display svg image
  flutter_svg: ^1.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.9.0"

  flutter_lints: ^1.0.0



flutter_icons:
  image_path: "assets/icons/icon2.png" 
  android: true
  ios: true
  #set icon with "flutter pub run flutter_launcher_icons:main"


flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/


